# Programming Assignment # 2: Numerical Python

# Importing the numerical python library to make it possible to use array functions

In [2]:
# importing the numerical python library
import numpy as np

# Problem 2.1 Normalization Problem
 ## This code gets a random 5x5 array and normalizes it using the formula $$ Z = \frac{x - \bar{X}}{\sigma} $$ The normalized array is then saved as a .npy file and is then loaded to check if the array was properly saved.

In [13]:
# Problem 1 

# initializing a random array as X
X = np.random.random((5,5))

# Printing the random array
print("Random Array:") 
print(X)

# initializing the mean and getting the mean of the X array
mean = X.mean()

# # initializing the Standard Deviation and getting the STD of the X array
std = X.std()

# Normalizing the X array by using the formula
Z = (X - mean)/std

# Saving the normalized Array into X_normalized.npy
np.save('X_normalized.npy', Z)

# Printing and checking to see if the array is saved properly
np.load('X_normalized.npy')

Random Array:
[[0.92595761 0.05189627 0.9325863  0.70022891 0.19592079]
 [0.8884627  0.11952346 0.31282238 0.58022888 0.38606296]
 [0.09065001 0.8203578  0.9578928  0.28357238 0.8763241 ]
 [0.66518643 0.95381264 0.49245591 0.86473604 0.25018444]
 [0.36252383 0.99913671 0.03112143 0.34125763 0.53625008]]


array([[ 1.178992  , -1.52440329,  1.19949397,  0.48083288, -1.07894805],
       [ 1.06302353, -1.31523828, -0.71738164,  0.10968327, -0.49085492],
       [-1.40454136,  0.85238101,  1.27776475, -0.80784932,  1.0254799 ],
       [ 0.37244954,  1.26514518, -0.16179084,  0.98963905, -0.91111529],
       [-0.5636594 ,  1.40532856, -1.58865805, -0.62943388, -0.02633932]])

# Problem 2.2 Divisible by 3 problem
 ## This code requires us to generate a 10x10 array with the squares of the first 100 positive integers. It then checks which elements of the array are divisible by 3 it is then saved into an .npy file and is loaded to see if the array was properly saved. Sample Output: ([9, 36, 81, 144, 225, ...])
 

In [20]:
# Problem 2

# Creating an array of the first 100 positive integers
Array_100_integers = np.arange(1,101)

# Getting the square of those integers
Squared_100_Integers = Array_100_integers**2

# Reshaping the array into a 10x10 array
New_10x10_Array = Squared_100_Integers.reshape(10,10)

# Finding which elements of the array are divisible by 3
divisible_by_3 = New_10x10_Array[New_10x10_Array % 3 == 0]

# Saving the elements divisible by 3 into div_by_3.npy
np.save('div_by_3.npy', divisible_by_3)

# Printing and checking to see if the array is saved properly
np.load('div_by_3.npy')

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])