# Programming Assignment # 2: Numerical Python

# Importing the numerical python library to make it possible to use array functions

In [5]:
# importing the numerical python library
import numpy as np

# Problem 2.1 Normalization Problem
 ## This code gets a random 5x5 array and normalizes it using the formula $$ Z = \frac{x - \bar{X}}{\sigma} $$ The normalized array is then saved as a .npy file and is then loaded to check if the array was properly saved.

In [7]:
# Problem 1 

# initializing a random array as X
X = np.random.random((5,5))

# Printing the random array
print("Random Array:") 
print(X)

# initializing the mean and getting the mean of the X array
mean = X.mean()

# # initializing the Standard Deviation and getting the STD of the X array
std = X.std()

# Normalizing the X array by using the formula
Z = (X - mean)/std

# Saving the normalized Array into X_normalized.npy
np.save('X_normalized.npy', Z)

# Printing and checking to see if the array is saved properly
print("Normalized array:") 
np.load('X_normalized.npy')

Random Array:
[[0.57994728 0.76115007 0.00619444 0.61014918 0.5475257 ]
 [0.33568215 0.9191503  0.85321929 0.54071781 0.223665  ]
 [0.9402342  0.24856531 0.28392321 0.32310232 0.78733811]
 [0.28925861 0.53113805 0.90079259 0.46620498 0.03942647]
 [0.68818477 0.0569138  0.48027142 0.27009897 0.38405147]]
Normalized array:


array([[ 0.35603184,  1.01927084, -1.74402007,  0.46657691,  0.23736226],
       [-0.53802813,  1.59758378,  1.35626288,  0.21244401, -0.94803365],
       [ 1.67475513, -0.85689346, -0.72747637, -0.58407288,  1.11512437],
       [-0.70794772,  0.17738014,  1.53039081, -0.06028809, -1.6223841 ],
       [ 0.75220302, -1.55837691, -0.00880207, -0.77807591, -0.36098662]])

# Problem 2.2 Divisible by 3 problem
 ## This code requires us to generate a 10x10 array with the squares of the first 100 positive integers. It then checks which elements of the array are divisible by 3 it is then saved into an .npy file and is loaded to see if the array was properly saved. Sample Output: ([9, 36, 81, 144, 225, ...])
 

In [20]:
# Problem 2

# Creating an array of the first 100 positive integers
Array_100_integers = np.arange(1,101)

# Getting the square of those integers
Squared_100_Integers = Array_100_integers**2

# Reshaping the array into a 10x10 array
New_10x10_Array = Squared_100_Integers.reshape(10,10)

# Finding which elements of the array are divisible by 3
divisible_by_3 = New_10x10_Array[New_10x10_Array % 3 == 0]

# Saving the elements divisible by 3 into div_by_3.npy
np.save('div_by_3.npy', divisible_by_3)

# Printing and checking to see if the array is saved properly
np.load('div_by_3.npy')

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])